<a href="https://colab.research.google.com/github/shuvamoy1983/Machine-learning-Tutorial/blob/master/tensorTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [ ]:
pip install tensor

     |████████████████████████████████| 51kB 3.8MB/s 
     |████████████████████████████████| 3.1MB 12.0MB/s 
     |████████████████████████████████| 61kB 5.6MB/s 
     |████████████████████████████████| 296kB 42.5MB/s 
     |████████████████████████████████| 61kB 7.2MB/s 
     |████████████████████████████████| 51kB 5.4MB/s 
     |████████████████████████████████| 245kB 46.5MB/s 
     |████████████████████████████████| 81kB 9.0MB/s 
     |████████████████████████████████| 13.7MB 27.9MB/s 
     |████████████████████████████████| 51kB 4.9MB/s 
  Created wheel for tensor: filename=tensor-0.3.6-cp36-none-any.whl size=71571 sha256=19d9a17f873c0c0dead5ff59181ab7af7f14a9043d44d36a6f3b7eae5a1eafc9
  Stored in directory: /root/.cache/pip/wheels/32/ba/ac/dbd210e9db9e5d549b3d98c57713684c5768298f259b1925ef
  Created wheel for construct: filename=construct-2.10.56-cp36-none-any.whl size=56879 sha256=f9e8d96d0521dfc1ab06b2b24cffa85de0922ea53f572ecd6c99298880f1a265
  Stored in directory: /root/.cach

In [1]:
import tensorflow as tf


Initialization of Tensor Flow

In [8]:
x=tf.constant([[2,3,4],[4,5,6]],shape=(2,3),dtype=float)

In [9]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [4., 5., 6.]], dtype=float32)>

In [16]:
x=tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 1], dtype=int32)>