<a href="https://colab.research.google.com/github/shuvamoy1983/Machine-learning-Tutorial/blob/master/tensorTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [ ]:
pip install tensor

     |████████████████████████████████| 51kB 3.8MB/s 
     |████████████████████████████████| 3.1MB 12.0MB/s 
     |████████████████████████████████| 61kB 5.6MB/s 
     |████████████████████████████████| 296kB 42.5MB/s 
     |████████████████████████████████| 61kB 7.2MB/s 
     |████████████████████████████████| 51kB 5.4MB/s 
     |████████████████████████████████| 245kB 46.5MB/s 
     |████████████████████████████████| 81kB 9.0MB/s 
     |████████████████████████████████| 13.7MB 27.9MB/s 
     |████████████████████████████████| 51kB 4.9MB/s 
  Created wheel for tensor: filename=tensor-0.3.6-cp36-none-any.whl size=71571 sha256=19d9a17f873c0c0dead5ff59181ab7af7f14a9043d44d36a6f3b7eae5a1eafc9
  Stored in directory: /root/.cache/pip/wheels/32/ba/ac/dbd210e9db9e5d549b3d98c57713684c5768298f259b1925ef
  Created wheel for construct: filename=construct-2.10.56-cp36-none-any.whl size=56879 sha256=f9e8d96d0521dfc1ab06b2b24cffa85de0922ea53f572ecd6c99298880f1a265
  Stored in directory: /root/.cach

In [2]:
import tensorflow as tf


Initialization of Tensor Flow

In [ ]:
x=tf.constant([[2,3,4],[4,5,6]],shape=(2,3),dtype=float)

In [ ]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
x=tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
x=tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
x=tf.eye(3) ##identifyng matrix
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
x=tf.random.normal((3,3),mean=0.0,stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.4339271 , -0.54042584,  0.30231947],
       [-0.36223915, -0.63334   , -0.20457107],
       [-0.7043122 ,  1.1730131 , -0.8075742 ]], dtype=float32)>

In [ ]:
x=tf.random.uniform((1,3),minval=0,maxval=1)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.8110423 , 0.30540347, 0.32542443]], dtype=float32)>

In [3]:
x=tf.range(start=1,delta=2,limit=10)

In [8]:
tf.cast(x,dtype=tf.float64)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

##Mathematical Operation

In [9]:
x=tf.constant([2,3,4])
y=tf.constant([3,4,5])
z=tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [10]:
z=tf.subtract(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1, -1, -1], dtype=int32)>

In [12]:
z=tf.multiply(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 12, 20], dtype=int32)>

In [13]:
z=tf.tensordot(x,y,axes=0)
z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 6,  8, 10],
       [ 9, 12, 15],
       [12, 16, 20]], dtype=int32)>

In [16]:
x=tf.constant([[2,3,4],[3,4,5]])
y=tf.constant([[1,2,3],[1,3,2]])
tf.add(x,y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 7],
       [4, 7, 7]], dtype=int32)>

In [20]:
tf.tensordot(x,y,axes=0)

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 2,  4,  6],
         [ 2,  6,  4]],

        [[ 3,  6,  9],
         [ 3,  9,  6]],

        [[ 4,  8, 12],
         [ 4, 12,  8]]],


       [[[ 3,  6,  9],
         [ 3,  9,  6]],

        [[ 4,  8, 12],
         [ 4, 12,  8]],

        [[ 5, 10, 15],
         [ 5, 15, 10]]]], dtype=int32)>